"""Seeds the four required legal policies into app.db's `policies` table at
startup, idempotently (see db.upsert_policy()). Originally slotted for
Phase 8 (which will add founder-facing editing/versioning UI on top of
this), but created here in Phase 4 because the signup/consent flow and the
public legal routes both need real, distinct content before Phase 8 is
reached -- Phase 1's /auth/consent already links to these.

This is placeholder-quality legal text, not a substitute for actual legal
review -- explicitly flagged in the plan as needing jurisdiction-specific
review before relying on it, especially the refund policy internationally
(EU/UK consumer cooling-off rules can override a no-refund policy). Do not
present this as final legal advice to the founder.
"""
from app import db

POLICY_VERSION = "2026-09-05"

_TERMS_OF_SERVICE = """\
# Terms of Service

Effective {effective_date}

## 1. What Meeting Saathi is

Meeting Saathi is a Chrome extension and web service that records your Google Meet \
calls (with your device's microphone and tab audio, once you click Start Recording) \
and uses AI to generate three documents from the conversation: Minutes of Meeting \
(MOM), Meeting Analysis, and Business Process Flow.

## 2. Your account

You need a verified email address to create an account. You are responsible for \
keeping your account credentials and any paired devices/extensions secure.

## 3. Recording responsibility

**You are solely responsible for informing meeting participants that the call is \
being recorded, and for obtaining any consent or permission required by law in your \
jurisdiction before recording.** Meeting Saathi does not verify or manage this for \
you.

## 4. Free trial and subscriptions

New accounts receive 3 free completed meetings. A meeting that fails or never \
captures audio does not count against this allowance. After the free allowance is \
used, a paid subscription (billed monthly or yearly) is required for further \
meetings, subject to a maximum meeting duration and fair-use limits described at \
signup and on the pricing page.

## 5. AI-generated content

Documents generated by Meeting Saathi are produced by an AI model and may contain \
errors, omissions, or misinterpretations. You are responsible for reviewing any \
generated document before relying on it or sharing it with others.

## 6. Acceptable use

You agree not to use Meeting Saathi to record meetings without the legally required \
consent of participants, or to use the service in any way that violates applicable \
law.

## 7. Termination

We may suspend or terminate an account that violates these terms. You may delete \
your account at any time from your account settings.

## 8. Changes to these terms

We may update these terms from time to time. Material changes will be reflected by \
a new effective date above.
"""

_PRIVACY_POLICY = """\
# Privacy Policy

Effective {effective_date}

## 1. What we collect

- Account information: your name and email address.
- Meeting content: audio you record, and the transcript, speaker names, and \
documents generated from it.
- Usage information: which features you use, and technical logs needed to operate \
and debug the service.

## 2. How we use it

Meeting content is processed by third-party AI services (currently Google's Gemini \
and, where configured, AssemblyAI) solely to produce your transcripts and \
documents. We do not sell your data.

## 3. Data retention and deletion

You can request deletion of an individual meeting's data or your entire account \
from your account settings. Deleting a meeting removes its transcript and generated \
documents; deleting your account additionally revokes any paired extension access \
and cancels any active subscription.

## 4. Third-party processors

We use payment processors (Razorpay) to handle subscription billing, and email \
providers to send verification codes and notifications. These providers process \
data only as needed to provide their service to us.

## 5. Security

We take reasonable measures to protect your data, including encrypting data in \
transit and restricting access to meeting content to what's needed to operate the \
service. No system is completely secure, and we cannot guarantee absolute security.

## 6. Your rights

Depending on your jurisdiction, you may have rights to access, correct, or delete \
your personal data, or to object to certain processing. Contact us through the \
feedback page to exercise these rights.
"""

_REFUND_POLICY = """\
# Refund and Cancellation Policy

Effective {effective_date}

## 1. Free trial

Every account starts with 3 free completed meetings, with no payment required. Use \
this to evaluate whether Meeting Saathi meets your needs before subscribing.

## 2. Subscriptions

Monthly and yearly subscriptions are billed in advance. **Payments are generally \
non-refundable once a billing period has started**, except where required by \
applicable law, or in the case of a duplicate charge or a billing error on our \
part.

## 3. Cancellation

You may cancel your subscription at any time from your account settings. \
Cancellation stops future renewals; you retain access to paid features through the \
end of the period you already paid for.

## 4. Jurisdiction-specific rights

This policy does not limit any statutory refund or cancellation right you have \
under the law of your country (for example, cooling-off periods that may apply to \
consumers in the European Union or United Kingdom). Where such a right applies, it \
takes precedence over this policy.

## 5. Contact

If you believe you were charged in error, contact us through the feedback page and \
we will review it.
"""

_AI_DISCLAIMER = """\
# AI Disclaimer

Effective {effective_date}

## AI-generated content may be wrong

Meeting Saathi uses an AI model to transcribe your meetings and generate the \
Minutes of Meeting, Meeting Analysis, and Business Process Flow documents. Like any \
AI system, it can make mistakes: it may mishear or mistranscribe what was said, \
misattribute a statement to the wrong speaker, omit something that was discussed, \
or draw an incorrect conclusion.

## Human review is required

You should review every AI-generated document before relying on it, sharing it with \
a client or colleague, or using it to make a decision. Meeting Saathi is a drafting \
aid, not a substitute for your own judgment.

## No professional advice

Generated documents are not legal, financial, or professional advice, even if their \
content resembles such advice (for example, a Business Process Flow describing a \
compliance process). Consult a qualified professional for decisions that require \
one.
"""

_POLICIES = {
    "terms_of_service": ("Terms of Service", _TERMS_OF_SERVICE),
    "privacy_policy": ("Privacy Policy", _PRIVACY_POLICY),
    "refund_policy": ("Refund and Cancellation Policy", _REFUND_POLICY),
    "ai_disclaimer": ("AI Disclaimer", _AI_DISCLAIMER),
}

# The fifth required consent (see app.auth.REQUIRED_CONSENT_POLICIES) is
# "recording_consent" -- an acknowledgment, not a standalone policy
# document, so it isn't seeded here as a page; it's presented inline on the
# signup consent screen and the extension's recording-setup screen (Phase
# 8's remaining surfacing work), same wording as Terms of Service section 3.
RECORDING_CONSENT_ACKNOWLEDGMENT = (
    "I understand that I am responsible for informing meeting participants and "
    "obtaining any consent or permission required by law before recording."
)


def seed_policies() -> None:
    for policy_type, (title, content_template) in _POLICIES.items():
        content = content_template.format(effective_date=POLICY_VERSION)
        db.upsert_policy(policy_type, POLICY_VERSION, title, content, POLICY_VERSION)
